### ISSUE TITLE
💥TODO for the Participants of Synthax🔥

### ISSUE THREAD

**Issue by subhayu99** [subhayu99/PyScripts#7]
# Aim
```
PR = number of Pull Requests (PR) currently open by you
while(TRUE):
    if(PR <= 1):
        Select any of the program files you want to work on from this link---> https://github.com/subhayu99/PyScripts/tree/master/Scripts/TODO_Scripts
        Now, do as per the instructions (TODO) given  in the file
        Once, completed with the task remove all the comments (starting with #) inside the file
        Open a Pull Request for the same
        PR += 1
    else:
        Wait, until PR <= 1
```

**Comment by subhayu99** [comment]
@DeepNinja07x @shalini-kumari2000 @sana990
I assign you people to this issue. Each of you should choose atleast 1 unique code file to work on and make a PR by 16th September.

**Comment by DeepNinja07x** [comment]
@subhayu99, I will be working on CheckGreater.py, ListComprehension.py, ListSearch.py, and ListSort.py program

**Comment by DeepNinja07x** [comment]
Rest @shalini-kumari2000 and @sana990 ... Each of you choose any 3 among the remaining

**Comment by subhayu99** [comment]
@DeepNinja07x I'll ask you to wait for them to choose first as I think you can solve all of them.

**Comment by DeepNinja07x** [comment]
@shalini-kumari2000 and @sana990 
please choose the program you want to work on by today's afternoon. And while creating the Pull Request mention this issue as:
"This is in response to issue #7". So, it'll be easier to track.

**Comment by shalini-tiwari** [comment]
@subhayu99 & @DeepNinja07x  I will do 1)BinaryToDecimal.py  2)DecimalToBinary.py  & 3)MaxNum.py

**Comment by subhayu99** [comment]
@shalini-kumari2000 
NOTE: Create PR for each completed solution.

**Comment by DeepNinja07x** [comment]
Yeah, it's very important **One file per Pull Request (PR)**. If you modify all the files at the same time and create a PR it will not get accepted.
